# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idconsulta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('crm', models.CharField(max_length=30)),
                ('especialidade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf_paciente', models.IntegerField(max_length=9)),
                ('data_de_nascimento', models.IntegerField()),
                ('endereco', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('telefone_fixo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='cpf_paciente',
            field=models.ManyToManyField(to='consulta.Paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='crm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.Medico'),
        ),
    ]
