# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_de_nascimento',
            field=models.DateTimeField(),
        ),
    ]
