# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_auto_20170125_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_de_nascimento',
            field=models.DateField(),
        ),
    ]
