# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_auto_20170125_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='cpf_paciente',
        ),
        migrations.AddField(
            model_name='consulta',
            name='cpf_paciente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horario_final',
            field=models.DateField(blank=True, null=True, verbose_name='Hora final'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horario_inicial',
            field=models.DateField(blank=True, null=True, verbose_name='Hora inicial'),
        ),
    ]
