# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_auto_20170130_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='cpf_paciente',
        ),
        migrations.AddField(
            model_name='consulta',
            name='cpfpaciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consulta.Paciente'),
        ),
    ]
